### PR TITLE
Implementing Feedback on Signup

### PR DESCRIPTION
**Pull request by eliemugenzi**
### What does this PR do?
- Implement the feedback I received from the Demo
### Description of the task to be completed?
- After successful registration, the user should not see `Login` and `Signup` in the header again.
- Verify account header should not be visible in case the verification is done.

### CODE REVIEW

**Review by EmyRukundo — APPROVED** [review]

**Review by Diama1 — APPROVED** [review]
Good Job!

**Review by rukundoeric — APPROVED** [review]

**Comment by deschantkn** [comment]
Hello @eliemugenzi, I was trying to signup and I noticed that the gender form input does not save the user's sex. If I choose a sex option and submit it is null in the database.

**Review by deschantkn — CHANGES_REQUESTED** [review]
Hello @eliemugenzi, I was trying to signup and I noticed that the gender form input does not save the user's sex. If I choose a sex option and submit it is null in the database.

**Comment by eliemugenzi** [comment]
> Hello @eliemugenzi, I was trying to signup and I noticed that the gender form input does not save the user's sex. If I choose a sex option and submit it is null in the database.

Thank you @deschantkn, Let me look at it.

**Comment by eliemugenzi** [comment]
I worked on the feedback, @deschantkn.

**Review by deschantkn — APPROVED** [review]

**Pull request merged**
